### ISSUE TITLE
First UI iteration

### ISSUE THREAD

**Issue by pwalsh** [openspending/subsidystories.eu#1]
# Description

We are building a small app for a subset of data served in openspending. This app will provide a curated view onto that data, as well as other data and stories that are related.

Original wireframes here: https://github.com/os-data/eu-structural-funds/issues/191#issue-184208296

We will do several iterations on the design. The goal of this first issue is not to pay much attention to design at all, but rather, just to get all the core elements setup in an app, for further design + data iterations.
# Tasks
- [x] copy the basics of [os-admin](https://github.com/openspending/os-admin) as the starting point for your app. This gives you the following:
  - a setup for angular and some basic templates
  - usage of the [OS style guide](https://github.com/openspending/os-style-guide) which this app should follow
  - an existing pattern for building fronted assets, favoured by the core OS app developers @akariv and @kravets-levko
- [x] Strip out what you don't need from your copy of the os-admin base. This should leave you with some type of skeleton with a main page, and whatever angular machinery we are using for routing to other pages
- [x] Implement a basic template for the three pages in the wireframes 
  - The header and footer of the os style guide are important for now. We might change them a little later
  - use D3 probably for the map
  - do a basic layout like the wireframes for the main content areas. for the actual content, especially the data points outside of the maps, provide some mock data for now.

**Comment by pwalsh** [comment]
@akariv if there are any specific points for the framework do make them known. I'll assign to Goce tomorrow when he accepts the invite.

**Comment by gocemitevski** [comment]
Pushed first set of templates here: https://github.com/openspending/subsidystories.eu

**Comment by gocemitevski** [comment]
Now available for preview at:
- http://labs.openspending.org/subsidystories.eu/index.html
- http://labs.openspending.org/subsidystories.eu/country.html

**Comment by DianaMPG** [comment]
@gocemitevski I just want to follow up on this. What are the agreed next steps?

**Comment by gocemitevski** [comment]
@DianaMPG I suppose, integrate these static mock-ups in an Angular application.

cc @pwalsh

**Comment by pwalsh** [comment]
I don't see much point in proceeding from this first iteration that we have until:
- we have an API to the data in OpenSpending, which we need to be in sync with @akariv on
- we have the updated style guide which we need to be in sync with @akariv and @smth on

**Comment by akariv** [comment]
@pwalsh we should have by EOD a dataset in OpenSpending which we will be able to query using the API and create embeddable visualisations upon it.
It might be a good time to move forward with the implementation of the website.

**Comment by pwalsh** [comment]
@akariv 

Ok. We'll need to have some type of understanding of the API calls to get all the data points.

**Comment by pwalsh** [comment]
@gocemitevski as a first next step, we can start the process of converting what you have to angular. Can you sync with @kravets-levko and @akariv on this.

**Comment by cyberbikepunk** [comment]
@gocemitevski I wanted to attract you attention to the `geography` folder in the repo. I put in there all the `geojson` data that you need to draw the boundaries according the `nuts` codes. Have a look.

**Comment by pwalsh** [comment]
@akariv do we have a version of the data now that can be queried? If yes, we'll need some examples that match the data points in the UI so that @gocemitevski can get started. We can continue that discussion in https://github.com/openspending/subsidystories.eu/issues/2
